FROM patmconnolly/compiler:el9
ARG VERSION
WORKDIR /
RUN dnf install -y openssl cyrus-sasl groff-base diffutils
RUN curl -O https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-${VERSION}.tgz && gunzip -c openldap-${VERSION}.tgz | tar xfB - && rm openldap-${VERSION}.tgz && cd /openldap-${VERSION} && ./configure && make depend && make && make test && make install && cd / && rm -rf /openldap-${VERSION}
EXPOSE 389
ENV SUFFIX="dc=example,dc=com"
ENV ROOTDN="cn=Manager,dc=example,dc=com"
ENV ROOTPW="secret"
ENV DEBUGLEVEL="0"
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/bin/bash", "-c", "/entrypoint.sh $SUFFIX $ROOTDN $ROOTPW && ulimit -n 1024 && /usr/local/libexec/slapd -F /usr/local/etc/slapd.d -d $DEBUGLEVEL"]