FROM patmconnolly/compiler:el9
ARG VERSION
RUN dnf install -y openssl cyrus-sasl groff-base diffutils
RUN curl -O https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-${VERSION}.tgz
RUN gunzip -c openldap-${VERSION}.tgz | tar xfB -
RUN rm openldap-${VERSION}.tgz
WORKDIR /openldap-${VERSION}/
RUN ./configure; make depend; make; make test; make install
WORKDIR /
EXPOSE 389
ENV SUFFIX="dc=example,dc=com"
ENV ROOTDN="cn=Manager,dc=example,dc=com"
ENV ROOTPW="secret"
ENV DEBUGLEVEL="0"
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/bin/bash", "-c", "/entrypoint.sh $SUFFIX $ROOTDN $ROOTPW && ulimit -n 1024 && /usr/local/libexec/slapd -d $DEBUGLEVEL"]